services:
  tamuzapp:
    container_name: winebrowserapp
    image: myridia/wine_browser_app 
    ports:
      - "5800:5800"
      - "5900:5900"      
    volumes:
      #- ./tamuz/:/root/.wine/drive_c/tamuz
      - ./autohotkey:/root/.wine/drive_c/autohotkey
      - ./startapp.sh:/startapp.sh  
    environment:
     - DARK_MODE=1
     - DISPLAY_WIDTH=1200
     - DISPLAY_HEIGHT=800
     - USER_ID=0
     - GROUP_ID=0     
     - STARTUP_SCRIPT=notepad
     - WEB_FILE_MANAGER=1
     - WEB_FILE_MANAGER_ALLOWED_PATHS=/
    tty: true





    
